### ISSUE TITLE
canvas is undefined

### ISSUE THREAD

**Issue by willroyMyles** [lionix-team/react-image-markup#2]
hi, im trynig to use your library and its return an error saying canvas is null, from - 
src/assets/js/methods.js:31

any help would be greatly appreciated

**Comment by arunzone** [comment]
Same here
`const circleModeParams = { fill: 'blue',stroke: 'white' }
  useEffect(() => {
    editor.current.set('circle',circleModeParams)
  }, [])
<Editor height="700" width="700" ref={editor} />`


got this error
`TypeError: Cannot set property 'isDrawingMode' of undefined
drag
src/assets/js/methods.js:31
  28 |   set(state.currentTool)
  29 | }
  30 | export const drag = () => {
\> 31 |   canvas.isDrawingMode = false;
  32 |   canvas.forEachObject(object => {
  33 |     object.selectable = true;
  34 |     object.evented = true;
View compiled
Editor.set
src/assets/js/methods.js:42
  39 |   new CropImage(canvas, false, false, true)
  40 | }
  41 | export const set = (type, params) => {
\> 42 |   drag();
  43 |   state.currentTool = type;
  44 |   switch (type) {
  45 |     case "text":
View compiled
(anonymous function)
src/main/front-end/src/component/patient/report/incident/IncidentDetailsPart5.js:22
  19 | const editor = useRef()
  20 | const circleModeParams = { fill: 'blue',stroke: 'white' }
  21 | useEffect(() => {
\> 22 |   editor.current.set('circle',circleModeParams)
     | ^  23 | }, [])
  24 | 
  25 | return {editor}`

**Comment by arunzone** [comment]
Figured out solution from the [Demo](https://github.com/lionix-team/react-image-markup-demo) code
